import { StyleSheet } from 'react-native';
import { HORIZONTAL_MARGIN } from '../../../utils/constants';
import { fontSize, hp, wp } from '../../../styles/metrics';
import { Colors } from '../../../styles';
import { fontFamily } from '../../../utils/functions';

export default StyleSheet.create({
  background: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: HORIZONTAL_MARGIN,
  },
  queryText: {
    fontSize: fontSize(18),
    lineHeight: fontSize(21.6),
    letterSpacing: -0.4,
    fontWeight: 'bold',
    color: Colors.white,
    marginHorizontal: HORIZONTAL_MARGIN,
    marginTop: hp(5),
    textAlign: 'center',
    marginBottom: hp(2),
    fontFamily: fontFamily.rf_medium,
  },
  infoContainer: {
    backgroundColor: Colors.white,
    padding: HORIZONTAL_MARGIN,
    borderRadius: wp(4.85),
    marginTop: hp(2.7),
  },
  subTitle: {
    fontSize: fontSize(11),
    lineHeight: fontSize(16),
    letterSpacing: -0.41,
    fontWeight: 'bold',
    color: Colors.greyish1,
    textTransform: 'uppercase',
    marginBottom: hp(0.55),
  },
  avatarNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(2.2),
  },
  arrowUpImage: {
    width: wp(8.5),
    height: wp(5.1),
    alignSelf: 'center',
    tintColor: Colors.white,
  },
  contactContainer: {
    // marginHorizontal: HORIZONTAL_MARGIN,
    padding: HORIZONTAL_MARGIN,
    borderRadius: wp(4.85),
    backgroundColor: Colors.white,
    alignItems: 'center',
    shadowColor: '#0D2F61',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    marginBottom: hp(5),
  },

  contact: {
    // flexDirection: 'row',
    // alignItems: 'center',
    marginTop: hp(2),
    marginBottom: hp(0.6),
    width: wp(19),
    height: wp(19),
    borderRadius: wp(19),
    borderWidth: 2,
    borderColor: Colors.primary4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  displayName: {
    fontSize: fontSize(18),
    lineHeight: fontSize(21.6),
    letterSpacing: -0.4,
    fontWeight: '600',
    color: Colors.greyish2,
    fontFamily: fontFamily.rf_regular,
  },
  taglineSubTitle: {
    fontSize: fontSize(14),
    lineHeight: fontSize(16),
    letterSpacing: -0.24,
    fontWeight: '400',
    color: Colors.greyish2,
    marginVertical: hp(1),
    textAlign: 'center',
    marginHorizontal: wp(5),
    fontFamily: fontFamily.rf_regular,
  },

  avatar: {
    width: wp(16),
    height: wp(16),
    borderRadius: wp(16),
    backgroundColor: Colors.primary1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: fontSize(20),
    fontWeight: 'bold',
    color: Colors.white,
  },
  userName: {
    fontSize: fontSize(20),
    lineHeight: fontSize(22),
    letterSpacing: -0.4,
    fontWeight: '600',
    color: Colors.greyish2,
    marginLeft: wp(4),
  },
  tagline: {
    fontSize: fontSize(13),
    lineHeight: fontSize(16),
    letterSpacing: -0.24,
    fontWeight: '500',
    color: Colors.greyish2,
  },
  statusContainer: {
    flex: 1,
    alignItems: 'center',
    paddingTop: hp(7.5),
    paddingHorizontal: HORIZONTAL_MARGIN,
  },
  statusDescription: {
    fontSize: fontSize(24),
    lineHeight: fontSize(34),
    letterSpacing: -0.4,
    fontWeight: '600',
    color: Colors.white,
    textAlign: 'center',
    fontFamily: fontFamily.rf_medium,
  },
  statusText: {
    fontSize: fontSize(20),
    lineHeight: fontSize(22),
    letterSpacing: -0.4,
    // fontWeight: '600',
    color: Colors.white,
    textAlign: 'center',
    marginTop: hp(2.2),
    marginBottom: hp(2.85),
    fontFamily: fontFamily.rf_regular,
  },
  cancelButton: {
    alignSelf: 'center',
    backgroundColor: Colors.destructive4,
    borderRadius: wp(3.4),
    padding: HORIZONTAL_MARGIN,
    width: wp(40),
    marginBottom: hp(2),
  },
  cancelButtonText: {
    color: Colors.white,
    fontSize: 17,
    fontWeight: '600',
    textAlign: 'center',
  },

  addFromButtonText: {
    color: Colors.white,
    fontSize: fontSize(16),
    fontWeight: '400',
    textAlign: 'center',
    lineHeight: fontSize(19),
    letterSpacing: -0.24,
    fontFamily: fontFamily.rf_regular,
  },
  addFromButton: {
    paddingVertical: hp(1.9),
    borderWidth: 0.9,
    borderRadius: wp(3.7),
    borderColor: Colors.white,
    marginHorizontal: wp(9),
  },
});
