import { StyleSheet } from 'react-native';
import { HORIZONTAL_MARGIN } from '../../../utils/constants';
import { fontSize, hp, wp } from '../../../styles/metrics';
import { Colors } from '../../../styles';
import { fontFamily } from '../../../utils/functions';

export default StyleSheet.create({
  background: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: wp(2.1),
    backgroundColor: '#F1F7FF',
  },
  queryText: {
    fontSize: fontSize(17),
    lineHeight: fontSize(22),
    letterSpacing: -0.4,
    fontWeight: 'bold',
    color: Colors.white,
    marginHorizontal: HORIZONTAL_MARGIN,
    marginTop: hp(10.6),
  },
  infoContainer: {
    backgroundColor: Colors.white,
    padding: HORIZONTAL_MARGIN,
    borderRadius: wp(4.85),
    marginTop: hp(2.7),
  },
  subTitle: {
    fontSize: fontSize(11),
    lineHeight: fontSize(16),
    letterSpacing: -0.41,
    fontWeight: 'bold',
    color: Colors.greyish1,
    textTransform: 'uppercase',
    marginBottom: hp(0.55),
  },
  avatarNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(2.2),
  },
  arrowUpImage: {
    width: wp(8.5),
    height: wp(5.5),
    alignSelf: 'center',
    tintColor: Colors.white,
  },
  contactContainer: {
    marginHorizontal: HORIZONTAL_MARGIN,
    padding: HORIZONTAL_MARGIN,
    borderRadius: wp(4.85),
    backgroundColor: Colors.white,
    alignItems: 'center',
    shadowColor: '#0D2F61',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    marginBottom: hp(9),
  },

  contact: {
    // flexDirection: 'row',
    // alignItems: 'center',
    marginTop: hp(2),
    marginBottom: hp(0.6),
    width: wp(19),
    height: wp(19),
    borderRadius: wp(19),
    borderWidth: 1,
    borderColor: Colors.primary5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  displayName: {
    fontSize: fontSize(20),
    lineHeight: fontSize(22),
    letterSpacing: -0.4,
    fontWeight: '600',
    color: Colors.greyish2,
  },
  taglineSubTitle: {
    fontSize: fontSize(13),
    lineHeight: fontSize(16),
    letterSpacing: -0.24,
    fontWeight: '500',
    color: Colors.greyish2,
    marginVertical: hp(1),
    textAlign: 'center',
    marginHorizontal: wp(5),
  },

  avatar: {
    width: wp(16),
    height: wp(16),
    borderRadius: wp(16),
    backgroundColor: Colors.primary1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: fontSize(20),
    fontWeight: 'bold',
    color: Colors.white,
  },
  userName: {
    fontSize: fontSize(20),
    lineHeight: fontSize(22),
    letterSpacing: -0.4,
    fontWeight: '600',
    color: Colors.greyish2,
    marginLeft: wp(4),
  },
  tagline: {
    fontSize: fontSize(13),
    lineHeight: fontSize(16),
    letterSpacing: -0.24,
    fontWeight: '500',
    color: Colors.greyish2,
  },
  statusContainer: {
    flex: 1,
    alignItems: 'center',
    // paddingTop: hp(7.5),
    // paddingHorizontal: HORIZONTAL_MARGIN,
    justifyContent: 'center',
  },
  statusDescription: {
    fontSize: fontSize(22),
    lineHeight: fontSize(28),
    letterSpacing: 0.35,
    fontWeight: 'bold',
    color: Colors.white,
    textAlign: 'center',
  },
  statusText: {
    fontSize: fontSize(17),
    lineHeight: fontSize(22),
    letterSpacing: -0.4,
    fontWeight: '600',
    color: Colors.white,
    textAlign: 'center',
    marginTop: hp(2.2),
    marginBottom: hp(2.85),
  },
  cancelButton: {
    alignSelf: 'center',
    // backgroundColor: Colors.white,
    borderRadius: wp(3.4),
    padding: HORIZONTAL_MARGIN + 2,
    width: '95%',
    marginBottom: hp(2),
    borderWidth: 1,
    borderColor: Colors.primary4,
  },
  cancelButtonText: {
    color: Colors.primary4,
    fontSize: fontSize(15),
    fontWeight: '500',
    textAlign: 'center',
    fontFamily: fontFamily.rf_regular,
  },

  connectionTitle: {
    fontSize: fontSize(18),
    lineHeight: fontSize(33),
    fontWeight: '700',
    letterSpacing: -0.4,
    color: Colors.destructive4,
    textAlign: 'center',
    marginTop: hp(1.7),
    marginBottom: hp(1.5),
    fontFamily: fontFamily.rf_medium,
  },
  connectionDesc: {
    fontSize: fontSize(14),
    lineHeight: fontSize(17.5),
    color: Colors.accent19,
    textAlign: 'center',
    fontFamily: fontFamily.rf_regular,
  },
});
