import { HTMLSource } from 'react-native-render-html';

export const source: HTMLSource = {
  html: `
    <p>The following terms and conditions (the "Terms" or “Agreement”) govern all use of the Parlapp website (the "Site") and the Parlapp mobile application (the “App”), the products and services made available on or at the Site or the App (collectively, the "Service"). The Service is owned and operated by Parlapp S.A.S.. ("Parlapp"). The Service is offered subject to your (the "User's") acceptance without modification of all of the terms and conditions contained herein and all other rules, policies and procedures that may be made available on the Service from time to time.</p>
    <p>These Terms together with the privacy policy available at ("Privacy Policy"), limited warranty available at ("Limited Warranty"), and other additional agreements referred to and/or linked herein, all of which are incorporated herein by reference, are, collectively, the “Agreement.”</p>
    <p>Please, read these Terms, Agreement and any additional terms applicable to your use of the Service before using it. By accessing or using the Service either as a registered user or not, you confirm your agreement to be bound by these Terms. These Terms expressly supersede prior agreements or arrangements with you regarding the use of the Service.</p>
    <p>Throughout these Terms, we use "Parlapp", “we”, “us” and “our” to refer to the Parlapp, offering our Service to you.</p>

    <h1>Changes to the Terms</h1>
    <p>We may modify these Terms at any time, at our sole discretion as they are subject to change. If we do so, we will let you know either by posting the modified Terms on the Service or through other communications such as the mobile phone number and email address registered in your account. It’s important that you review the Terms whenever we modify them because if you continue to use the Service after we have posted modified Terms on the platform, you are indicating to us that you agree to be bound by the modified Terms.</p>
    <p>If you do not agree to be bound by the modified Terms, then you may not use the Service anymore. Because our Service is evolving over time we may change or discontinue all or any part of the Service, at any time and without notice, at our sole discretion.</p>

    <h1>Eligibility, Account Registration and Security</h1>
    <p>The Service is designed to establish instant relationships between people to share and learn, using an audio exchange.</p>
    <p>You may need to register for an account to access some or all of our Service. Before you create an account, you confirm that you are eligible to use our Service. By using the Service, you warrant and represent that you are at least 13 years old or of the legal age in your jurisdiction old and you have the capacity, right and authority to enter a legal agreement and will abide by all the provisions of these Terms of Use. If you are not up to the legal age in your jurisdiction, your legal guardian or parent must consent to the content of these Terms.</p>
    <p>If you register for an account with Parlapp, you shall provide Parlapp with true, accurate and complete registration information (including, but not limited to your mobile telephone number and/or email address and a passcode you will use to access the Service). You will also keep your registration information accurate and up-to-date. Failure to do so shall constitute a breach of these Terms, which may result in immediate termination of your Parlapp account.</p>
    <p>By registering to use Parlapp, you agree that you will not:</p>
    <ol style="list-style-type: upper-roman;">
      <li>Select as your Username and Full Name names that you don’t have the right to use, or another person’s name with the intent to impersonate that person;</li>
      <li>Create an account for anyone other than yourself without such person's permission;</li>
      <li>be disrespectful when communicating with any other user of the Service;</li>
      <li>Record any portion of a conversation without the expressed consent of all of the speakers involved;</li>
      <li>Share information (on Parlapp or elsewhere) that the speaker explicitly stated was to be treated as “off the record”;</li>
      <li>Collect email addresses and/or other contact information of other users from the Service in order to send unsolicited emails or communications;</li>
      <li>Create a user name or Parlapp account that is subject to any rights of a person other than you without appropriate authorization;</li>
      <li>Create a user name that is a name that is otherwise offensive, vulgar or obscene or otherwise unlawful; or</li>
    </ol>
    <p>Parlapp reserves the right to refuse registration of or cancel a user name, at its sole discretion.</p>
    <p>You are solely responsible and liable for activity that occurs on your account and shall be responsible for maintaining the confidentiality of your Parlapp account and passcode. You shall never use another user's account without such other user's prior express permission. You accept responsibility for all activities that occur under your User Account you will immediately notify Parlapp in writing of any unauthorized use of your account or other account-related security breaches of which you are aware.</p>
    
    <h1>Access and Use of the Service</h1>
    <p>Subject to the terms and conditions of this Agreement, the software and services provided in connection with the Service is solely for your own personal use, and not for the use or benefit of any third party. Unless otherwise expressly authorized herein or in the Service, you agree not to display, publish, copy, modify, create derivatives from, upload, transfer, use, distribute, license, sell or resell for any commercial purposes, any portion of the Service, use of the Service, or access to the Service.</p>
    <p>Parlapp may change, discontinue or suspend the Service, including the availability of any feature, content or database, at any time, with or without notice. Parlapp may also impose limits on certain features and services or restrict your access to parts or all of the Service without notice or liability. You agree that Parlapp may establish general rules and limits concerning the use of the Service, including the maximum period of time that content or other data will be retained by the Service and the maximum storage space that will be allocated on your behalf on Parla’s servers. You agree that Parlapp has no responsibility or liability for the deletion or failure to store any data or other content maintained or uploaded by the Service.</p>
    <p>You may not copy, modify, distribute, sell, or lease any part of the Service, nor may you reverse engineer or attempt to extract the source code of that software, unless laws prohibit these restrictions or you have our written permission to do so. You agree not to remove, alter, or obscure any copyright, trademark, or other proprietary rights notice on or in the Service. You shall not sell, license, rent, or otherwise use or exploit any Content for commercial (whether or not for profit) use or in any way that violates any third party right.</p>

    <h1>Third-party Distribution Channels</h1>
    <p>Parla’s App and Service may be made available through the Apple App Store, the Google Play Store or other distribution channels. If you obtain Parla’s App and Service through such distribution channel, you may be subject to additional terms of the distribution channel. These Terms of Service are between you and us only, and not with the distribution channel. To the extent that you utilize any other third party products and services in connection with your use of our Service, you agree to comply with all applicable terms of any agreement for such third party products and services.</p>
    <p>This paragraph applies to any App that you acquire from the Apple App Store or use on an iOS device:</p>
    <ol style="list-style-type: upper-roman;">
      <li>Parlapp and you acknowledge that these Terms and Conditions are concluded between Parlapp and you only, and not with Apple. As between Parlapp and Apple, Parlapp, not Apple, is solely responsible for the App and the content thereof.</li>
      <li>You may not use the App in any manner that is in violation of or inconsistent with the Usage Rules set forth for the App in, or otherwise be in conflict with, the App Store Terms of Service.</li>
      <li>Your license to use the App is limited to a non-transferable license to use the App on any Apple-branded products that you own or control and as permitted by the Usage Rules set forth in the Apple Media Services Terms and Conditions.</li>
      <li>Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App.</li>
      <li>In the event of any failure of the App to conform to any applicable warranty, you may notify Apple, and Apple will refund the App purchase price to you (if applicable) and, to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App, and any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be, as between Parlapp and Apple, Parla’s sole responsibility, to the extent it cannot be disclaimed under applicable law.</li>
      <li>Parlapp and you acknowledge that Parlapp, not Apple, is responsible for addressing any claims of you or any third party relating to App or your possession and/or use of that App, including, but not limited to: (i) product liability claims; (ii) any claim that the App fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection, privacy, or similar legislation.</li>
      <li>In the event of any third party claim that the App or the end-user’s possession and use of that App infringes that third party’s intellectual property rights, as between Parlapp and Apple, Parlapp, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim.</li>
      <li>You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.</li>
      <li>If you have any questions, complaints or claims with respect to the App, you should direct them to Parlapp as follows: email to info@parla.chat.</li>
      <li>You must comply with applicable third party terms of agreement when using the App.</li>
      <li>Parlapp and you acknowledge and agree that Apple, and Apple’s subsidiaries, are third party beneficiaries of these Terms and Conditions with respect to the App, and that, upon your acceptance of these Terms and Conditions, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms and Conditions against you with respect to the App as a third party beneficiary thereof.</li>
    </ol>

    <h1>Intellectual Property</h1>
    <p>All content, including audio, video, text, data, code, software, pictures, graphics, sound, music, or other materials on the site that has been contributed by users of the Parlapp app is designated as open content. All such content may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted as long as:</p>
    <ol style="list-style-type: upper-roman;">
      <li>It is not used for commercial purposes or displayed on a commercial website (except on message boards);</li>
      <li>In Parla’s sole opinion it is not used to denigrate Parlapp, its Service, or its community, and does not violate Parla’s rights in any other manner;</li>
      <li>Prominent attribution is given to Parlapp when sharing such content, and</li>
      <li>Attribution is given to the original author(s) as identified on the Parlapp Service.</li>
    </ol>
    <p>Parlapp maintains compilation copyright on your content. Your content may be reproduced in part for non-commercial purposes as described above, but may not be reproduced as a whole through any medium without the express permission of Parlapp.</p>
    <p>All rights in the Parlapp logo, graphics, design, sound files, pictures and other files, and the selection and arrangement thereof and any other content not contributed by users ("Your Content") are the property of Parlapp and/or its affiliates or licensors.</p>
    <p>The Parlapp name and logo are registered trademarks of Parlapp. All other trademarks displayed on Parlapp's Service are the trademarks of their respective owners and are not intended to imply any endorsement or affiliation between Parlapp and such owners.</p>
    <p>Parlapp disclaims any responsibility for the content of any third-party content provided through or on our Service. We do desire to respect all copyrights and respond promptly when notified of the infringement of those rights.</p>
 
    <h1>Content Owned by Parlapp</h1>
    <p>You agree that all content and materials (including audio, video, text, data, code, software, pictures, graphics, sound, music, or other materials, collectively, "Content") delivered via the Service or otherwise made available by Parlapp via the Service are protected by copyrights, trademarks, service marks, patents, trade secrets or other proprietary rights and laws. Except as expressly authorized by Parlapp in writing, you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from such materials or content. However, as a user of the Parlapp Service, you may print or download a reasonable number of copies of the materials or content for your own informational purposes; provided, that you retain all copyright and other proprietary notices as described in the “Intellectual Property” clause above. Reproducing, copying or distributing any content, materials or design elements on the Service for any other purpose is strictly prohibited without the express prior written permission of Parlapp. The foregoing does not apply to your own User Content that you legally uploaded to the Service.</p>

    <h1>Feedback, Your Content and Submissions</h1>
    <p>The Parlapp App may permit you to add and share certain content such as posts, photos, links, text, over the phone conversation, and other files and information about yourself (“Content”), to share with other users of the Parlapp Service. The submission of communications (such as commentary on other users content) and other content submitted by users of the Service and the hosting, sharing, and/or publishing of such content(s) (“Your Content”).</p>
    <p>Parlapp provides a feedback system that provides a means through which Users can share their opinions of other Users privately and/or publicly, and Parlapp does not monitor, influence, contribute to or censor these opinions. You acknowledge and agree that User feedback benefits the platform, all Users, and the efficiency of the platform and you specifically request that Parlapp utilize and/or post such feedback about users, including yourself, on User Profiles and elsewhere on the platform.</p>
    <p>In order to protect the integrity of the feedback system and protect Users from abuse, Parlapp reserves the right (but is under no obligation) to remove posted feedback or information that, in Parla’ sole judgment, violates the Terms of Service or negatively affects our platform, diminishes the integrity of the feedback system or otherwise is inconsistent with the business interests of Parlapp. You acknowledge and agree that you will notify Parlapp of any error or inaccurate statement in your feedback results, including the feedback information, and that if you do not do so, Parlapp may rely on the accuracy of such information.</p>
    <p>You shall be solely responsible for all and the consequences of uploading, sharing, displaying, posting or publishing content on and/or via the Service. You agree that Parlapp has no liability with respect to any of your content, and you hereby irrevocably release Parlapp and its officers and directors, employees, agents, representatives and affiliates, from any and all liability arising out of or relating to your content or any part thereof.</p>
    <p>By submitting your content to Parlapp, or displaying, publishing, or otherwise posting any content on or through the Parlapp Service, you hereby grant Parlapp a worldwide, non-exclusive, perpetual, royalty-free, fully paid, sublicensable and transferable license to reproduce, distribute, modify (such as by editing or otherwise creating derivatives), display your content in accordance with the terms of this Agreement. You agree not to contest any modifications made by Parlapp and hereby waives any claims with respect thereto. For clarity, the foregoing license grant to Parlapp does not affect your ownership or license rights in your content made available on the Service, including the right to grant additional licenses to the content in any of your submitted content.</p>
    <p>In connection with your content made available on the Parlapp Service, you affirm, represent, and warrant that:</p>
    <ol style="list-style-type: upper-roman;">
      <li>You own or have the necessary rights, licenses, consents, and permissions to use and authorize Parlapp to use such content and to enable inclusion and use of such content in the manner contemplated by the Service and this Terms;</li>
      <li>You have the written consent, release, and/or permission of every identifiable individual in your content to use the name or likeness of every such identifiable individual to enable inclusion and use of the content in the manner contemplated by the Service and the Terms herein;</li>
      <li>The posting of your content on or through the Service or otherwise does not violate the privacy rights, publicity rights, intellectual property rights, contract rights, or any other rights of any individual or entity. You agree to pay all royalties, fees, and other monies owing to any individual or entity by reason of any content posted by you to or through the Service.</li>
    </ol>
    <p>Parlapp does not endorse any User Content, submission, opinion, recommendation, or advice expressed therein, and Parlapp expressly disclaims all responsibility or liability in connection with User Content Submission(s). You acknowledge the global nature of the Internet and you agree to comply with all local rules and laws regarding your use of the Service, including as it concerns online conduct and acceptable content.</p>
    <p>You acknowledge that Parlapp does not pre-screen content, and agree that Parlapp has the right to, in its sole discretion, remove any User Content at any time (with or without notice).</p>
    <p>You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information about the Service, provided by you to Parlapp are non-confidential and Parlapp can unrestrictedly use and disseminate them for any purpose, commercial or other, without acknowledgment or compensation to you.</p>

    <h1>Obscene and Offensive Content</h1>
    <p>We are not responsible for any obscene or offensive content that you receive or view from others while using our Service. However, if you do receive or view such content, please contact us by email at info@parla.chat so that we can investigate the issue. Although we are not obligated to do so, we reserve the right to monitor, investigate, and remove obscene or offensive material posted to our Service.</p>

    <h1>Representation and Prohibited Use</h1>
    <p>Although we are committed to providing a safe user experience, we do not guarantee that the platform, or any content in it, will be safe, error-free or uninterrupted, or that it will be free from bugs or viruses.</p>
    <p>From time to time, access to the Service may be interrupted, suspended or restricted, including because of a fault, error, unforeseen circumstances or scheduled maintenance. We shall not be liable to you for any loss or damage that you may suffer as a result of the Service being unavailable at any time for any reason.</p>
    <p>You agree, undertake and confirm that your use of the platform shall be strictly in accordance with the following binding guidelines. You shall not host, display, upload, modify, publish, transmit, update or share any information which:</p>
    <ol style="list-style-type: upper-roman;">
      <li>Belongs to another person and to which you do not have any right to make use of or promotes an illegal or unauthorized copy of another person's copyrighted work such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices;</li>
      <li>Is grossly harmful, harassing, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;</li>
      <li>Is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual or provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;</li>
      <li>Involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming" or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish the value of, surreptitiously intercept or expropriate any system, data or personal information;</li>
      <li>Promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;</li>
      <li>Provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses; contains video, photographs, or images of another person (with a minor or an adult);</li>
      <li>Tries to gain unauthorized access or exceeds the scope of authorized access to the Service or to profiles, blogs, communities, account information, bulletins, or other areas of the Service or solicits passcodes or personal identifying information for commercial or unlawful purposes from other users.</li>
      <li>Interferes with another user's use and enjoyment of the Service or any other individual's user and enjoyment of similar services;</li>
      <li>Refers to any website or URL that, in our sole discretion, contains material that is inappropriate for the Service or contains content that would be prohibited or violates the letter or spirit of these Terms of Use.</li>
    </ol>

    <h1>Cyberbullying and Internet Harassment</h1>
    <p>Cyberbullying and Internet harassment are prohibited within our community. Although we support free speech rights, such rights are limited where the purpose or effect of the expression is to bully, harass, threaten, ridicule, embarrass, and/or intimidate others. This is particularly true in matters involving race, ethnicity, national origin, religion, gender, sex, sexual orientation, physical disability, and/or mental condition.</p>
    <p>Suppose we decide, in our sole discretion, that you have committed cyber-bullying acts or Internet harassment. In that case, we reserve the right to unilaterally suspend or ban your use of our Service immediately with or without notice to you. Although we are not obligated to do so, we reserve the right to monitor, investigate, and remove material posted to the Service that we determine constitutes cyber-bullying or Internet harassment.</p>
    <p>If we suspect that the cyberbullying acts or Internet harassment constitute illegal activity, we may, in our sole discretion, provide information to law enforcement or other government officials for purposes of investigating the misconduct. Examples of illegal conduct include, but are not limited to, threats of violence, sending sexually explicit images, and stalking others. This sharing of information is consistent with our Privacy Policy terms governing the suspected illegal activity.</p>

    <h1>User Interactions and Assumption of Risk</h1>
    <p>We are not responsible for verifying Users that make use of the platform. As such, it is your responsibility to be careful when communicating or interacting with other Users. You understand and agree that Parlapp does not, and cannot, confirm that each User is who he/she/they claim to be. You assume all risks associated with Users with whom you come into contact. If you have any disputes or issues with any User you agree to pursue any remedies directly with the applicable User, and you release Parlapp, its subsidiaries, and their respective employees, directors, and agents from all claims, demands, and damages of every kind (actual and consequential and direct and indirect) known and unknown, suspected and unsuspected, disclosed and undisclosed, to the fullest extent permitted by law.</p>

    <h1>Software and Software Updates</h1>
    <p>For the software you are authorized by Parlapp to download via the Service, Parlapp grants you a personal, nontransferable, nonsublicensable, nonexclusive license to use such software solely for User's personal, non-commercial use, and only in accordance with these Terms provided by Parlapp.</p>
    <p>The App may cause the Product to communicate with the Parlapp servers to deliver the functionality and certain features to the app in order to keep the app running smoothly. We may from time to time develop patches, bug fixes, updates, upgrades and other modifications to improve or otherwise modify the performance of the App and related Service (“Updates”). These Updates may be installed on the software distribution platform of App Store or Google play or the other platforms by providing additional notice.</p>

    <h1>Communication Services and Fees</h1>
    <p>When you make use of the Parlapp Service, you understand that you are responsible for all internet fees, carrier data plans, and other associated fees. In particular, the Service includes services available via a mobile device, including via an application downloaded and installed on a mobile device and the upload and download of content via the mobile device. Standard charges, data rates and other charges from your wireless service provider may apply. You agree that we may communicate with you about Parlapp and the Service by SMS, MMS, text message or other electronic means on your mobile device and that certain information about your use of the mobile services may be communicated to us. If you change or deactivate your mobile phone number, you agree to promptly update your Parlapp account information so that your messages are not sent to the person who acquired your previous number.</p>

    <h1>Privacy</h1>
    <p>By making use of the Parlapp Service, you further agree to be bound by the Parlapp Privacy Policy. Kindly read our privacy policy as it will help you understand how and why we collect, make use of and share information that we collect about you and the rights that you have over your information.</p>

    <h1>Third-Party Content and Resources</h1>
    <p>The Service may permit you to link to other websites, services or resources on the Internet, and other websites, services or resources may contain links to the App; (“Third-Party Content”). These other websites are not under Parlapp's control, and you acknowledge that Parlapp is not liable or responsible for the content, accuracy, functions, legality, appropriateness or any other aspect of such websites or resources. The inclusion of any such link does not imply endorsement by Parlapp.</p>
    <p>You further acknowledge and agrees that Parlapp shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any content, goods, information, or services available on or through any such website or resource.</p>

    <h1>Copyright and Infringement Notification</h1>
    <p>Parlapp respects the intellectual property of others and asks its users of the platform to do the same. Parla’s Service may not be used to transmit, retransmit, distribute, post, or store any material that is in violation of any rights of any person including rights protected by copyright, trade secret, patent, or other intellectual property or similar laws or regulations.</p>
    <p>Parlapp has established procedures for enforcing this statement which is designed to be in accord with the Digital Millennium Copyright Act. If you believe that your copyrighted work has been copied and is accessible on any of Parla’s Service in a way that constitutes copyright infringement, please notify us.</p>
    <p>
    In order to be valid, the notification must be in writing and must contain the following information:</p>
    <ol style="list-style-type: upper-roman;">
      <li>A description of the copyrighted content or other intellectual property that you claim has been infringed;</li>
      <li>A statement by you that you have a good faith belief that the use of this content or intellectual property is not authorized and for which reason;</li>
      <li>A detailed description of where this content or intellectual property is located on the Service, in order for us to find it;</li>
      <li>Your address, telephone number, and email address;</li>
      <li>A signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest;</li>
      <li>A statement by you, made under penalty of perjury, that the above information provided by you in the notification is accurate and that you are the copyright or intellectual property owner or authorized to act on the behalf of the copyright or intellectual property owner.</li>
    </ol>
    <p>Please note that any person who knowingly misrepresents to Parlapp that material is infringing shall be liable to Parlapp and/or the alleged infringer for any damages (including costs and attorneys’ fees) suffered or incurred by Parlapp and/or the alleged infringer as a result of Parla’s reliance on such misrepresentation and removing or disabling access to such material. Similarly, any person who knowingly misrepresents to Parlapp that the material was removed or access blocked by mistake or misidentification shall be liable to Parlapp and/or the copyright owner or its authorized licensee for any damages (including costs and attorneys’ fees) suffered or incurred by Parlapp and/or the copyright owner or its authorized licensee as a result of Parla’s relying on such misrepresentation and replacing such removed or blocked material.</p>

    <h1>Warranty Disclaimer</h1>
    <p>THE SERVICE (INCLUDING, WITHOUT LIMITATION, THE APP, THE SITE, CONTENT, MATERIALS AND THE OPPORTUNITY OF USERS TO CONNECT WITJ EACH OTHER) IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON- INFRINGEMENT.</p>
    <p>PARLA MAKES NO PROMISE OR WARRANTY THAT (I) THE SERVICE WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; (II) THE RESULTS OF USING THE SERVICE (OR ANY USER SUBMISSION(S)) WILL MEET THE USER'S REQUIREMENTS;
    THAT THE CONDUCT OR QUALITY OF ANY THIRD-PARTY CONTENT ACCESSED THROUGH THE PARLA SERVICE WILL BE SUITABLE. YOUR USE OF THE PARLA SERVICE IS SOLELY AT YOUR OWN RISK.</p>

    <h1>Limitation of Liability</h1>
    <p>YOU AGREE THAT TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PARLA WILL NOT BE LIABLE TO YOU UNDER ANY THEORY OF LIABILITY.</p>
    <p>IN NO EVENT SHALL PARLA, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, VENDORS OR SUPPLIERS BE LIABLE UNDER CONTRACT, TORT, STRICT LIABILITY, NEGLIGENCE OR ANY OTHER LEGAL THEORY WITH RESPECT TO THE SERVICE (OR ANY CONTENT, PROGRAMS OR INFORMATION AVAILABLE THROUGH THE SERVICE): (I) FOR ANY LOST PROFITS OR SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER, SUBSTITUTE GOODS OR SERVICES (HOWEVER ARISING), (II) FOR ANY BUGS,</p>
    <p>VIRUSES, TROJAN HORSES, OR THE LIKE (REGARDLESS OF THE SOURCE OF ORIGINATION), (III) FOR ANY ERRORS OR OMISSIONS IN ANY CONTENT OR INFORMATION OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT OR INFORMATION POSTED, EMAILED, TRANSMITTED OR OTHERWISE MADE AVAILABLE AT OR THROUGH THE PARLA SERVICE, OR (IV) FOR ANY DIRECT DAMAGES IN EXCESS OF (IN THE AGGREGATE) USD$100.00 OR ANY AMOUNT YOU PAID TO PARLA IN THE LAST SIX MONTHS FOR THE SERVICES GIVING RISE TO THE CLAIM.</p>
    <p>IN ADDITION, PARLA SHALL NOT BE LIABLE FOR ANY LOSS OR LIABILITY RESULTING, DIRECTLY OR INDIRECTLY, FROM THE USER'S INABILITY TO ACCESS OR OTHERWISE USE THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY DELAYS OR INTERRUPTIONS DUE TO ELECTRONIC OR MECHANICAL EQUIPMENT FAILURES, DENIAL OF SERVICE ATTACKS, PROCESSING FAILURES, TELECOMMUNICATIONS OR INTERNET PROBLEMS OR UTILITY FAILURES).</p>
    <p>
    YOU AGREE THAT IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICE OR WITH THESE TERMS OF SERVICE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USE OF THE SERVICE.</p>

    <h1>Termination</h1>
    <p>Parlapp may terminate User's access to all or any part of the Service at any time, with or without cause, effective upon notice thereof to User (provided that, if Parlapp determines there may be an immediate threat to Parlapp, it may terminate such access without notice). You acknowledge that Parlapp may terminate accounts that are inactive over a period of 12 months.</p>
    <p>Upon termination notice from Parlapp, User will (i) no longer access (or attempt to access) the Service and (ii) delete all software (and copies thereof) provided in connection with the Service. All provisions of this Agreement that by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers and limitations of liability.</p>

    <h1></h1>
    <ol style="list-style-type: lower-alpha;">
      <li><strong>Choice of Law and Forum:</strong> This Agreement shall be governed by French law. You understand and agree that any claim or dispute they have against Parlapp will be resolved by a court located in Paris (France) subject to the arbitration clause below or unless otherwise agreed between the parties.</li>
      <li><strong>Dispute Resolution; Arbitration:</strong> Any dispute, controversy or claim arising out of this contract, or the breach, termination or invalidity thereof shall be settled by arbitration in accordance with Rules of Arbitration of the French Arbitration Association.</li>
      <li><strong>Severability:</strong> If any provision of these Terms is determined by a court to be unlawful, unenforceable, or invalid as a whole, the parties agree that the court shall amend that provision to achieve as nearly as possible the same effect as the original provision and the remainder of these Terms will remain in effect.</li>
      <li><strong>Waiver:</strong> No delay or omission by Parlapp to exercise any right occurring upon any noncompliance on your part with respect to any of the terms of this Terms shall impair any such right or power or be construed to be a waiver thereof. Any waiver by us of any of the covenants, conditions, or agreements to be performed by you shall not be construed to be a waiver of any succeeding breach thereof or of any covenant, condition, or agreement herein contained.</li>
      <li><strong>Assignability:</strong> A user may not assign these Terms, or any of its rights or obligations hereunder, without Parla’s prior written consent in the form of a written instrument signed by a duly authorized representative of Parlapp. We may freely assign this Agreement and the other Terms without the User’s consent. Any attempted assignment or transfer in violation of this subsection will be null and void. Subject to the foregoing restrictions, the Terms herein are binding upon and will inure to the benefit of the successors, heirs, and permitted assigns of the parties</li>
      <li><strong>Entire Agreement:</strong> These Terms with other policies presented to you, constitute the entire agreement between you and us with respect to the platform and its use and supersedes all prior agreements, proposals, communications between the parties, and understandings,
      whether oral or written.</li>
      <li><strong>Section Titles:</strong> The section titles in these Terms of Service are for convenience only and have no legal or contractual effect.</li>
    </ol>

    <h1>Questions or Complaints?</h1>
    <p>Feedback, comments, requests for technical support, and other communications relating to the App and the Service should be directed to us. Please contact us at info@parla.chat.</p>
`,
};
