export const defaultLocalConfig = {
  reportDescriptionReuired: false,
  addButtonDelayCaller: 0,
  addButtonDelayReceiver: 0,
  knowHowsMin: 5,
  taglineAudioDuration: 60,
  taglineLength: 180,
  isAvatarRequired: false,
  isAudioTagRequired: true,
  splashScreenDuration: 2,
  initialCallDuration: 300,
  aditionalCallDuration: 300,
  popUpDisplayDuration: 30,
  endCallDurationAfterFailed: 5,
  matchAcceptedWaitDuration: 30,
  matchActiveDuration: 30,
  searchtagLength: 30,
  userMatchingDuration: 120,
  usersLimit: 5,
  userQueryLimit: 3,
  timeWarningLimit: 60,
  batchTimeDuration: 30,
  querierResponserContactingDuration: 80,
};
