export const strings = {
  parla: 'Parla Room',
  notification_received: 'Parla Room Notification Received',
  notification_accepted: 'Parla Room Notification Search Candidates Received',
  notification_accepted_click: 'Parla Room Notification Accepted Click',
  notification_decline: 'Parla Room Notification Decline Click',
  notification_not_now: 'Parla Room Notification Not Now Click',
  notification_close: 'Parla Room Notification Close',
  parlaroom_started: 'Parlaroom Started',
  call_end: 'Call end',
  ntification_found: 'Parla room Notification Found',
  notification_cancelled: 'Parla room Notification cancelled',
  notification_add_time: 'Parla room Notification Add Time',
  click: 'Click',
  parla_room_success_class_create: 'Parla Room Success class Create',
  cancel: 'Cancel',
  microphone_click: 'Parla Room Microphone click',
  volume_click: 'Parla Room Volume click',
  parla_room_leave: 'Parla Room Leave',
  parla_room_end_call: 'Parla Room End call',
  parla_room_cancel: 'Parla Room cancel',
  request_time_is_out: 'Request time is out',
  parla_room_call_feedback: ' Parla Room Call Feedback',
  add_min: ' Parla Room Call Add 5 min',
  api_base_url: 'API BASE URL',
  api_request: 'API Request',
  api_respose: 'API RESPONSE',
  forground_notification: 'FOREGROUND NOTIFICATION',
  notification_open: 'NOTIFICATION OPEN APP:',
  availabilityStatus: 'Availability_Status',
  subscriptionSubscribed: 'Subscription changed to isActive',
};
