import { StyleSheet } from 'react-native';
import { Colors } from '../../../styles';
import { fontSize, hp, wp } from '../../../styles/metrics';
import { AUTH_HORIZONTAL_SPACE, HORIZONTAL_MARGIN } from '../../../utils/constants';
import { fontFamily } from '../../../utils/functions';
import { ISIOS } from '../../../utils/hooks';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.secondary5,
  },
  mainContainer: {
    height: ISIOS ? hp(35) : hp(33),
    alignItems: 'center',
    marginBottom: hp(7.5),
  },
  queryContainer: {
    paddingHorizontal: AUTH_HORIZONTAL_SPACE,
    marginTop: hp(3.8),
    marginBottom: hp(1),
  },
  query: {
    fontSize: fontSize(18),
    lineHeight: fontSize(21.4),
    letterSpacing: -0.4,
    fontWeight: '600',
    color: Colors.primary4,
    textAlign: 'center',
    fontFamily: fontFamily.rf_regular,
  },
  currentText: {
    fontSize: fontSize(12),
    lineHeight: fontSize(16),
    letterSpacing: -0.04,
    fontWeight: '500',
    color: Colors.greyish2,
    fontFamily: fontFamily.rf_regular,
  },
  contactContainer: {
    marginHorizontal: HORIZONTAL_MARGIN,
    padding: HORIZONTAL_MARGIN,
    borderRadius: wp(4.85),
    backgroundColor: Colors.white,
    alignItems: 'center',
    shadowColor: '#0D2F61',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    marginBottom: hp(9),
  },
  contact: {
    // flexDirection: 'row',
    // alignItems: 'center',
    marginTop: hp(2),
    marginBottom: hp(0.6),
    width: wp(19.4),
    height: wp(19.4),
    borderRadius: wp(19.4),
    borderWidth: 1,
    borderColor: Colors.primary5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowUpImage: {
    width: wp(8.5),
    height: wp(5.5),
    alignSelf: 'center',
    tintColor: Colors.white,
  },
  avatar: {
    width: wp(16.26),
    height: wp(16.26),
    borderRadius: wp(16.26),
    backgroundColor: Colors.primary1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: fontSize(20),
    fontWeight: 'bold',
    color: Colors.white,
  },
  displayName: {
    fontSize: fontSize(18),
    lineHeight: fontSize(21.6),
    letterSpacing: -0.4,
    fontWeight: '600',
    color: Colors.accent19,
    fontFamily: fontFamily.rf_regular,
  },
  myDisplayName: {
    fontSize: fontSize(17),
    lineHeight: fontSize(20),
  },
  taglineTtitle: {
    marginBottom: hp(0.55),
  },
  taglineSubTitle: {
    fontSize: fontSize(14),
    lineHeight: fontSize(17.5),
    letterSpacing: -0.24,
    fontWeight: '400',
    color: Colors.greyish27,
    marginVertical: hp(1),
    textAlign: 'center',
    marginHorizontal: wp(5),
    fontFamily: fontFamily.rf_regular,
  },
  youInfoContainer: {
    flexGrow: 1,
    marginTop: hp(2.7),
    paddingHorizontal: AUTH_HORIZONTAL_SPACE,
  },
  timeInfo: {
    paddingHorizontal: AUTH_HORIZONTAL_SPACE,
    paddingBottom: hp(9),
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  currentTime: {
    flex: 0.4,
  },
  maxTime: {
    flex: 0.5,
  },
  extendTime: {
    alignItems: 'center',
  },
  addTimeButton: {
    // marginTop: hp(0.55),
    paddingVertical: hp(1.4),
    paddingHorizontal: HORIZONTAL_MARGIN,
    backgroundColor: Colors.primary2,
    borderRadius: wp(9),
  },
  addTimeButtonDisabled: {
    // marginTop: hp(0.55),
    paddingVertical: hp(1.4),
    paddingHorizontal: HORIZONTAL_MARGIN,
    backgroundColor: Colors.greyish7,
    borderRadius: wp(9),
  },
  addTimeButtonText: {
    fontSize: fontSize(15),
    lineHeight: fontSize(18),
    letterSpacing: -0.4,
    fontWeight: '500',
    color: Colors.white,
    marginHorizontal: wp(3),
    fontFamily: fontFamily.rf_regular,
  },
  extendTimeText: {
    fontSize: fontSize(10),
    lineHeight: fontSize(12),
    letterSpacing: -0.4,
    fontWeight: '600',
    color: Colors.greyish3,
    marginTop: hp(0.8),
    fontFamily: fontFamily.rf_regular,
    textTransform: 'uppercase',
  },
  addTimeButtonTextDisabled: {
    fontSize: fontSize(17),
    fontWeight: '600',
    color: Colors.greyish8,
  },
  timeCounter: {
    fontSize: fontSize(28),
    lineHeight: fontSize(28),
    letterSpacing: 0.38,
    color: Colors.greyish2,
    marginTop: hp(1.5),
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: AUTH_HORIZONTAL_SPACE,
    paddingBottom: hp(1.5),
    // borderTopWidth: 0.3,
    // borderColor: Colors.greyish25,
    paddingTop: hp(3.5),
  },
  controllersButtons: {
    minWidth: wp(8.7),
    minHeight: wp(8.7),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  leaveRoomButton: {
    backgroundColor: Colors.destructive4,
    padding: HORIZONTAL_MARGIN,
    minWidth: wp(40),
    borderRadius: wp(3.4),
  },
  leaveRoomButtonText: {
    fontSize: fontSize(17),
    lineHeight: fontSize(22),
    letterSpacing: -0.4,
    fontWeight: '600',
    color: Colors.white,
    textAlign: 'center',
  },
  progressMain: {
    marginBottom: hp(1),
    marginHorizontal: wp(4.2),
  },
  progressContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  progressBar: {
    width: wp(91.5),
    height: 5,
    borderColor: Colors.accent18,
    borderWidth: 1,
    backgroundColor: Colors.accent18,
    borderRadius: 2.5,
  },
  informWindow: {
    marginTop: wp(3),
    marginHorizontal: wp(13),
    alignItems: 'center',
    justifyContent: 'center',

    borderRadius: 20,
    paddingVertical: wp(4),
  },
  infoText: {
    fontFamily: fontFamily.rf_regular,
    fontSize: fontSize(15),
    fontWeight: '500',
    textAlign: 'center',
    color: Colors.primary11,
    marginHorizontal: wp(5),
    marginTop: wp(2),
  },
  timeWarningText: {
    fontFamily: fontFamily.rf_regular,
    fontSize: fontSize(15),
    fontWeight: '500',
    textAlign: 'center',
    color: Colors.destructive4,
    marginHorizontal: wp(5),
    marginTop: wp(2),
  },
  yourContact: {
    color: Colors.greyish27,
    fontWeight: '600',
    fontFamily: fontFamily.rf_regular,
    fontSize: fontSize(10),
    lineHeight: fontSize(12),
    paddingTop: hp(6),
  },
});
